application: belbot
version: 1
runtime: python
api_version: 1
threadsafe: yes

runtime_config:
  python_version: 3

handlers:
- url: .*
  script: belbot.app

libraries:
- name: webapp2
  version: "2.5.2"
